version: '3'
services:
  app:
    build:
      context: .
      args:
        VARIANT: '3.1-bullseye'
        BUNDLER_VERSION: '2.3.14'
        RAILS_VERSIONS: '7.0.3'
        NODE_VERSION: '16'
    environment:
      PORT: 8080
      BINDING: 0.0.0.0
      GOOGLE_APPLICATION_CREDENTIALS: /google_key.json
    ports:
      - "8080:8080"
    volumes:
      - .:/sp-kakeibo
      - bundle-volume:/usr/local/bundle
      - ${GOOGLE_APPLICATION_CREDENTIALS}:/google_key.json
    command: sleep infinity
    restart: always
volumes:
  bundle-volume:

